services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - mqtt

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: consumer
    depends_on:
      - mqtt
      - api

  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile
    container_name: simulator
    depends_on:
      - mqtt

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api